### ISSUE TITLE
UUID.v1() generates unexpected timestamp

### ISSUE THREAD

**Issue by faseidl** [scravy/uuid-1345#5]
I generated an new UUID like this:

```
const code = UUID.v1();
```

This produced a reasonable looking UUID: `a8f5b990-1000-11a7-16a2-28cfe91bde25`

However, [decoding](http://blog.yahor.net/2016/04/online-uuid-decoder.html) the embedded timestamp produced value of:

```
1960-02-21 19:43:36 UTC
```

I was expecting a current timestamp.

**Comment by scravy** [comment]
I had a look at this and I have my doubts that the decoder you are linking is decoding the timestamp correctly.

The timestamps in UUID v1 are not unix timestamp, that is they do not count in seconds and they do not start in 1970. The count in one-hundred-nanosecond intervals since the switch to the gregorian calendar:

>   The timestamp is a 60-bit value.  For UUID version 1, this is
>   represented by Coordinated Universal Time (UTC) as a count of 100-
>   nanosecond intervals since 00:00:00.00, 15 October 1582 (the date of
>   Gregorian reform to the Christian calendar).

This is reflected in code here: https://github.com/scravy/uuid-1345/blob/master/index.js#L200
